# Generated by Django 2.0.1 on 2018-02-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cherrytea_app', '0002_charity_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='charitygroup',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
