# Generated by Django 2.0.1 on 2018-02-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cherrytea_app', '0003_charitygroup_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='donationplan',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
