# Generated by Django 2.0.1 on 2018-02-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cherrytea_app', '0004_auto_20180210_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationplan',
            name='last_fulfilled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationplan',
            name='status',
            field=models.CharField(choices=[('ACT', 'active'), ('SUS', 'suspended')], default='ACT', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donationplan',
            name='total_donated',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
