# Generated by Django 2.0.2 on 2018-02-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cherrytea_app', '0007_donation_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='useroptions',
            name='stripe_id',
            field=models.CharField(db_index=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
